Rebase against version 1.136.2-2

diff --git a/bin/live-snapshot b/bin/live-snapshot
--- a/bin/live-snapshot
+++ b/bin/live-snapshot
@@ -2,15 +2,17 @@
 
 # live-snapshot - utility to manage Debian Live systems snapshots
 #
-#   This program mount a device (fallback to /tmpfs under /mnt/snapshot
-#   and save the /live/cow (or a different dir) filesystem in it for reusing
-#   in another live-initramfs session. Look at manpage for more info.
+#   This program mounts a device (fallback to /tmpfs under $MOUNTP
+#   and saves the /live/cow (or a different directory) filesystem in it
+#   for reuse in another live-initramfs session.
+#   Look at the manpage for more informations.
 #
-# Copyright (C) 2006 Marco Amadori <marco.amadori@gmail.com>
+# Copyright (C) 2006-2008 Marco Amadori <marco.amadori@gmail.com>
+# Copyright (C) 2008 Chris Lamb <chris@chris-lamb.co.uk>
 #
-# This program is free software; you can redistribute it and/or modify
+# This program is free software: you can redistribute it and/or modify
 # it under the terms of the GNU General Public License as published by
-# the Free Software Foundation; either version 2 of the License, or
+# the Free Software Foundation, either version 3 of the License, or
 # (at your option) any later version.
 #
 # This program is distributed in the hope that it will be useful,
@@ -19,75 +21,65 @@
 # GNU General Public License for more details.
 #
 # You should have received a copy of the GNU General Public License
-# along with this program; if not, write to the Free Software
-# Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA
+# along with this program. If not, see <http://www.gnu.org/licenses/>.
 #
 # On Debian systems, the complete text of the GNU General Public License
-# can be found in /usr/share/common-licenses/GPL-2 file.
+# can be found in /usr/share/common-licenses/GPL-3 file.
 
-PROGRAM="$(basename $0)"
-VERSION=0.0.1
+# declare here two vars from /etc/live.conf because of "set -u"
+ROOTSNAP=""
+HOMESNAP=""
 
-# Source live conf
-if [ -e /etc/live.conf ]
-then
-	. /etc/live.conf
-else
-	USERNAME=$(cat /etc/passwd | grep "999" | cut -f1 -d ':')
-	HOSTNAME=$(hostname)
-fi
+set -eu
+
+. /usr/share/initramfs-tools/scripts/live-helpers
+
+LIVE_CONF="/etc/live.conf"
+. "${LIVE_CONF}"
 
 export USERNAME USERFULLNAME HOSTNAME
 
-# Source helper functions
-helpers="/usr/share/initramfs-tools/scripts/live-helpers"
+EXECUTABLE="${0}"
+PROGRAM=$(basename "${EXECUTABLE}")
 
-if [ -e "${helpers}" ]
-then
-	. "${helpers}"
-else
-	echo "Error: I cannot found helper functions \"${helpers}\"."
+# Needs to be available at run and reboot time
+SAFE_TMPDIR="/live"
+
+# Permits multiple runs
+MOUNTP="$(mktemp -d -p ${SAFE_TMPDIR} live-snapshot-mnt.XXXXXX)"
+DEST="${MOUNTP}/live-sn.cpio.gz"
+DEF_SNAP_COW="/live/cow"
+TMP_FILELIST="${PROGRAM}.list"
+
+# Command line defaults and declarations
+SNAP_COW="${DEF_SNAP_COW}"
+SNAP_DEV=""
+SNAP_OUTPUT=""
+SNAP_RESYNC_STRING=""
+SNAP_TYPE="cpio"
+SNAP_LIST="/etc/live-snapshot.list"
+
+Error ()
+{
+	echo "${PROGRAM}: error:" ${@}
 	exit 1
-fi
+}
 
-# Define LSB log_* functions.
-# Depend on lsb-base (>= 3.0-6) to ensure that this file is present.
-. /lib/lsb/init-functions
-
-MOUNTP=""
-COW=""
-DEV=""
-DEST=""
-TYPE=""
-DESKTOP_LINK=""
+panic ()
+{
+	Error ${@}
+}
 
 Header ()
 {
-	echo "${PROGRAM} - utility to do Debian Live snapshots"
+	echo "${PROGRAM} - utility to perform snapshots of Debian Live systems"
 	echo
-	echo "Usage: ${PROGRAM} [-c|--cow DIRECTORY] [-d|--device DEVICE] [-o|--output FILE] [-t|--type TYPE]"
-	echo "Usage: ${PROGRAM} [-r|--resync-string STRING]"
-	echo "Usage: ${PROGRAM} [-h|--help]"
-	echo "Usage: ${PROGRAM} [-u|--usage]"
-	echo "Usage: ${PROGRAM} [-v|--version]"
-}
-
-Usage ()
-{
-	MESSAGE=${1}
-
-	Header
-
-	echo
-	echo "Try \"${PROGRAM} --help\" for more information."
-
-	if [ ! -z "${MESSAGE}" ]
-	then
-		/bin/echo -e "${MESSAGE}"
-		exit 1
-	else
-		exit 0
-	fi
+	echo "usage: ${PROGRAM} [-c|--cow DIRECTORY] [-d|--device DEVICE] [-o|--output FILE] [-t|--type TYPE]"
+	echo "       ${PROGRAM} [-r|--resync-string STRING]"
+	echo "       ${PROGRAM} [-f|--refresh]"
+	echo "       ${PROGRAM} [-h|--help]"
+	echo "       ${PROGRAM} [-u|--usage]"
+	echo "       ${PROGRAM} [-v|--version]"
 }
 
 Help ()
@@ -96,21 +88,34 @@ Help ()
 
 	echo
 	echo "Options:"
-	echo "  -c, --cow: specifies the copy on write directory (default: /live/cow)."
-	echo "  -d, --device: specifies the output snapshot device (default: none)."
-	echo "  -o, --output: specifies the output image file (default: ${type} dependent)."
+	echo "  -c, --cow: copy on write directory (default: ${SNAP_COW})."
+	echo "  -d, --device: output snapshot device (default: ${SNAP_DEV:-auto})."
+	echo "  -o, --output: output image file (default: ${DEST})."
 	echo "  -r, --resync-string: internally used to resync previous made snapshots."
-	echo "  -t, --type: specifies the snapshot type between \"squashfs\", \"ext2\", \"ext3\" or \"cpio\".gz archive (default: cpio)"
-	/bin/echo -e "\nLook at live-snapshot(1) man page for more information."
+	echo "  -f, --refresh: try to sync a running snapshot."
+	echo "  -t, --type: snapshot filesystem type. Options: \"squashfs\", \"ext2\", \"ext3\", \"jffs2\" or \"cpio\".gz archive (default: ${SNAP_TYPE})"
+	echo
+	echo "Look at live-snapshot(1) man page for more information."
+
+	exit 0
+}
+
+Usage ()
+{
+	Header
+
+	echo
+	echo "Try \"${PROGRAM} --help\" for more information."
 
 	exit 0
 }
 
 Version ()
 {
-	echo "${PROGRAM}, version ${VERSION}"
+	echo "${PROGRAM}"
 	echo
 	echo "Copyright (C) 2006 Marco Amadori <marco.amadori@gmail.com>"
+	echo "Copyright (C) 2008 Chris Lamb <chris@chris-lamb.co.uk>"
 	echo
 	echo "This program is free software; you can redistribute it and/or modify"
 	echo "it under the terms of the GNU General Public License as published by"
@@ -134,57 +139,32 @@ Version ()
 	exit 0
 }
 
-Do_snapshot ()
+Try_refresh ()
 {
-	case "${TYPE}" in
-		squashfs)
-			echo "./tmp/exclude_list" > /tmp/exclude_list
-			( cd "${COW}" && find . -name '*.wh.*' >> /tmp/exclude_list )
-			mksquashfs "${COW}" "${DEST}" -ef /tmp/exclude_list || exit 1
-			rm /tmp/exclude_list
-			;;
+	FOUND=""
+	if [ -n "${ROOTSNAP}" ]; then
+		"${EXECUTABLE}" --resync-string="${ROOTSNAP}"
+		FOUND="Yes"
+	fi
 
-		cpio)
-			( cd "${COW}" && find . -path '*.wh.*' -prune -o -print0 | cpio --quiet -o0 -H newc | gzip -9c > "${DEST}" ) || exit 1
-			;;
+	if [ -n "${HOMESNAP}" ]; then
+		"${EXECUTABLE}" --resync-string="${HOMESNAP}"
+		FOUND="Yes"
+	fi
 
-		ext2|ext3)
-			DU_DIM="$(du -ks ${COW} | cut -f1)"
-			REAL_DIM="$(expr ${DU_DIM} + ${DU_DIM} / 20)" # Just 5% more to be sure, need something more sophistcated here...
-			genext2fs --size-in-blocks=${REAL_DIM} --reserved-blocks=0 --root="${COW}" "${DEST}" || exit 1
-			;;
-
-		*)
-			echo "Internal error."
-			exit 1
-			;;
-	esac
-}
-
-Is_same_mount ()
-{
-	dir1="$(Base_path ${1})"
-	dir2="$(Base_path ${2})"
-
-	if [ "${dir1}" = "${dir2}" ]
+	if [ -z "${FOUND}" ]
 	then
-		return 0
-	else
-		return 1
+		echo "No autoconfigured snapshots found at boot;" > /dev/null 1>&2
+		echo "(no resync string in ${LIVE_CONF})." > /dev/null 1>&2
+		exit 1
 	fi
 }
 
 Parse_args ()
 {
 	# Parse command line
-	ARGS="${1}"
-	ARGUMENTS="$(getopt --longoptions cow:,device:,output,resync-string:,type:,help,usage,version --name=${PROGRAM} --options c:d:o:t:r:,h,u,v --shell sh -- ${ARGS})"
-
-	if [ "${?}" != "0" ]
-	then
-		echo "Terminating." >&2
-		exit 1
-	fi
+	ARGS="${*}"
+	ARGUMENTS="$(getopt --longoptions cow:,device:,output,resync-string:,refresh,type:,help,usage,version --name=${PROGRAM} --options c:d:o:t:r:fhuv --shell sh -- ${ARGS})"
 
 	eval set -- "${ARGUMENTS}"
 
@@ -212,8 +192,13 @@ Parse_args ()
 				;;
 
 			-r|--resync-string)
-				SNAP_RSTRING="${2}"
+				SNAP_RESYNC_STRING="${2}"
 				break
+				;;
+
+			-f|--refresh)
+				Try_refresh
+				exit 0
 				;;
 
 			-h|--help)
@@ -234,115 +219,211 @@ Parse_args ()
 				;;
 
 			*)
-				echo "Internal error."; exit 1 ;;
+				Error "internal error."
+				;;
 
 		esac
 	done
 }
 
-Mount_device ()
-{
-	dev="${1}"
-
-	if [ ! -d "${MOUNTP}" ]
-	then
-		mkdir -p "${MOUNTP}"
-	fi
-
-	if [ -z "${dev}" ]
-	then
-		# create a temp
-		mount -t tmpfs -o rw tmpfs "${MOUNTP}"
-
-		if [ ! -L /home/${USERNAME}/Desktop/live-snapshot ]
-		then
-			ln -s "${MOUNTP}" /home/${USERNAME}/Desktop/live-snapshot
-		fi
-	else
-		if [ -b "${dev}" ]
-		then
-			try_mount "${dev}" "${MOUNTP}" rw
-		fi
-	fi
-}
-
 Defaults ()
 {
-	MOUNTP="/mnt/live-snapshot"
-	COW="/live/cow"
-	DEV=""
-	DEST="${MOUNTP}/live-sn.cpio.gz"
-	TYPE="cpio"
-	DESKTOP_LINK=/home/${USERNAME}/Desktop/live-snapshot
-
-	if [ -n "${SNAP_RSTRING}" ]
+	# Parse resync string
+	if [ -n "${SNAP_RESYNC_STRING}" ]
 	then
-		COW=$(echo "${SNAP_RSTRING}" | cut -f1 -d ':')
-		DEV=$(echo "${SNAP_RSTRING}" | cut -f2 -d ':')
-		DEST=$(echo "${SNAP_RSTRING}" | cut -f3 -d ':')
+		SNAP_COW=$(echo "${SNAP_RESYNC_STRING}" | cut -f1 -d ':')
+		SNAP_DEV=$(echo "${SNAP_RESYNC_STRING}" | cut -f2 -d ':')
+		DEST="${MOUNTP}/$(echo ${SNAP_RESYNC_STRING} | cut -f3 -d ':')"
 
 		case "${DEST}" in
 			*.cpio.gz)
-				TYPE="cpio"
+				SNAP_TYPE="cpio"
 				;;
 
 			*.squashfs)
-				TYPE="squashfs"
+				SNAP_TYPE="squashfs"
+				;;
+
+			*.jffs2)
+				SNAP_TYPE="jffs2"
 				;;
 
 			""|*.ext2|*.ext3)
-				TYPE="ext2"
+				SNAP_TYPE="ext2"
+				;;
+			*)
+				Error "unrecognized resync string"
+				;;
+		esac
+	elif [ -z "${SNAP_OUTPUT}" ]
+	then
+		# Set target file based on image
+		case "${SNAP_TYPE}" in
+			cpio)
+				DEST="${MOUNTP}/live-sn.cpio.gz"
 				;;
 
-			*)
-				Usage "Unregognized String"
+			squashfs|jffs2|ext2)
+				DEST="${MOUNTP}/live-sn.${SNAP_TYPE}"
+				;;
+
+			ext3)
+				DEST="${MOUNTP}/live-sn.ext2"
 				;;
 		esac
 	else
-		DEF_COW="/live/cow"
-
-		# Bad options handling
-		if [ -z "${SNAP_COW}" ]
-		then
-			COW="${DEF_COW}"
-		else
-			COW="${SNAP_COW}"
-		fi
-
-		case "${SNAP_TYPE}" in
-			"cpio"|"squashfs"|"ext2"|"ext3")
-				TYPE="${SNAP_TYPE}"
-				;;
-
-			"")
-				TYPE="cpio"
-				;;
-
-			*)
-				Usage "Error: unrecognized snapshot type"
-				;;
-		esac
-
-		#if [ -d
-		#if Is_same_mount
+		DEST="${SNAP_OUTPUT}"
 	fi
+}
 
-	# check vars
-	if [ ! -d "${COW}" ]
+Validate_input ()
+{
+	case "${SNAP_TYPE}" in
+		cpio|squashfs|jffs2|ext2|ext3)
+			;;
+
+		*)
+			Error "invalid filesystem type \"${SNAP_TYPE}\""
+			;;
+	esac
+
+	if [ ! -d "${SNAP_COW}" ]
 	then
-		Usage "Error: ${COW} is not a directory"
+		Error "${SNAP_COW} is not a directory"
 	fi
 
-	Mount_device ${DEV}
+	if [ "$(id -u)" -ne 0 ]
+	then
+		Error "you are not root"
+	fi
+}
+
+Mount_device ()
+{
+	case "${SNAP_DEV}" in
+		"")
+			# create a temp
+			mount -t tmpfs -o rw tmpfs "${MOUNTP}"
+			;;
+
+		*)
+			if [ -b "${SNAP_DEV}" ]
+			then
+				try_mount "${SNAP_DEV}" "${MOUNTP}" rw
+			fi
+			;;
+	esac
+}
+
+Do_filelist ()
+{
+	# BUGS: supports only cpio.gz types right now
+	TMP_FILELIST=$1
+	if [ -f "${SNAP_LIST}" ]
+	then
+		# Generate include list
+		for entry in $(cat "${SNAP_LIST}" | grep -v '^#.*$' | grep -v '^ *$')
+		do
+			if [ -f "${entry}" ]
+			then
+				printf "%s\000" "${entry}" >> "${TMP_FILELIST}"
+			elif [ -d "${entry}" ]
+			then
+				cd /
+				find "${entry}" -print0 >> "${TMP_FILELIST}"
+				cd "${OLDPWD}"
+			fi
+		done
+
+		if [ "${SNAP_COW}" = "${DEF_SNAP_COW}" ]
+		then
+			# Relative to rootfs
+			echo "/"
+		else
+			# Mostly "/home"
+			echo "${SNAP_COW}"
+		fi
+	else
+		cd "${SNAP_COW}"
+		find . -path '*.wh.*' -prune -o -print0 >> "${TMP_FILELIST}"
+		cd "${OLDPWD}"
+		echo "${SNAP_COW}"
+	fi
+}
+
+Do_snapshot ()
+{
+	TMP_FILELIST=$(mktemp -p "${SAFE_TMPDIR}" "${TMP_FILELIST}.XXXXXX")
+
+	case "${SNAP_TYPE}" in
+		squashfs)
+			echo ".${TMP_FILELIST}" > "${TMP_FILELIST}"
+			# Removing whiteheads of unionfs
+			cd "${SNAP_COW}"
+			find . -name '*.wh.*' >> "${TMP_FILELIST}"
+			cd "${OLDPWD}"
+			mksquashfs "${SNAP_COW}" "${DEST}" -ef "${TMP_FILELIST}"
+			;;
+
+		cpio)
+			WORKING_DIR=$(Do_filelist "${TMP_FILELIST}")
+			cd "${WORKING_DIR}"
+			cat "${TMP_FILELIST}" | cpio --quiet -o0 -H newc | gzip -9c > "${DEST}" || exit 1
+			cd "${OLDPWD}"
+			;;
+
+		ext2|ext3)
+			DU_DIM="$(du -ks ${SNAP_COW} | cut -f1)"
+			REAL_DIM="$(expr ${DU_DIM} + ${DU_DIM} / 20)" # Just 5% more to be sure, need something more sophistcated here...
+			genext2fs --size-in-blocks=${REAL_DIM} --reserved-percentage=0 --root="${SNAP_COW}" "${DEST}"
+			;;
+
+		jffs2)
+			mkfs.jffs2 --root="${SNAP_COW}" --output="${DEST}"
+			;;
+	esac
+
+	if [ -f "${TMP_FILELIST}" ]
+	then
+		rm -f "${TMP_FILELIST}"
+	fi
 }
 
 Clean ()
 {
-	if [ -n "${DEV}" ]
+	if [ -z "${SNAP_RESYNC_STRING}" ] && echo "${DEST}" | grep -q "${MOUNTP}"
 	then
+		echo "${DEST} is present on ${MOUNTP}, therefore no automatic unmounting the latter." > /dev/null 1>&2
+	else
 		umount "${MOUNTP}"
 		rmdir "${MOUNTP}"
-		#rm
+	fi
+}
+
+Warn_user ()
+{
+	if [ -z "${SNAP_RESYNC_STRING}" ]
+	then
+		case ${SNAP_TYPE} in
+			cpio|ext2|ext3)
+				echo "Please move ${DEST} (if is not already in it)" > /dev/null 1>&2
+				echo "in a supported writable partition (e.g ext3, vfat)." > /dev/null 1>&2
+				;;
+
+			squashfs)
+				echo "To use ${DEST} you need to rebuild your media or add it" > /dev/null 1>&2
+				echo "to your multisession disc under the \"/live\" directory." > /dev/null 1>&2
+				;;
+
+			jffs2)
+				echo "Please cat or flashcp ${DEST} to your partition in order to start using it." > /dev/null 1>&2
+				;;
+		esac
+
+		if grep -qv persistent /proc/cmdline
+		then
+			echo "Remember to boot this live system with \"persistent\" specified at boot prompt." > /dev/null 1>&2
+		fi
 	fi
 }
 
@@ -350,8 +431,11 @@ Main ()
 {
 	Parse_args "${@}"
 	Defaults
+	Validate_input
+	trap 'Clean' EXIT
+	Mount_device
 	Do_snapshot
-	Clean
+	Warn_user
 }
 
-Main "${@}"
+Main "${@:-}"
diff --git a/scripts/live b/scripts/live
--- a/scripts/live
+++ b/scripts/live
@@ -60,6 +60,21 @@ Arguments ()
                                 export FETCH
                                 ;;
 
+			hook=*)
+				HOOK="${ARGUMENT#hook=}"
+				export HOOK
+				;;
+
+			ftpfs=*)
+				FTPFS="${ARGUMENT#ftpfs=}"
+				export FTPFS
+				;;
+
+			httpfs=*)
+				HTTPFS="${ARGUMENT#httpfs=}"
+				export HTTPFS
+				;;
+
 			hostname=*)
 				HOSTNAME="${ARGUMENT#hostname=}"
 				LIVECONF="changed"
@@ -149,6 +164,12 @@ Arguments ()
 				export LIVE_MEDIA_TIMEOUT
 				;;
 
+			language=*|debian-installer/language=*)
+				language=${x#debian-installer/language=}
+				locale="$(lang2locale "$language")"
+				set_locale="true"
+				;;
+
 			locale=*|debian-installer/locale=*)
 				LOCALE="${ARGUMENT#*=}"
 				export LOCALE
@@ -227,11 +248,6 @@ Arguments ()
 			nokpersonalizer)
 				NOKPERSONALIZER="Yes"
 				export NOKPERSONALIZER
-				;;
-
-			nokwallet)
-				NOKWALLET="Yes"
-				export NOKWALLET
 				;;
 
 			nolanguageselector)
@@ -322,9 +338,9 @@ Arguments ()
 				mount -n -o bind /dev /root/dev
 
 				mkdir -p /root/var/run/network
-				chroot /root ifup -a
+				chroot /root dhclient eth0
 				chroot /root wget -P /tmp "${location}"
-				chroot /root ifdown -a
+				chroot /root ifconfig eth0 down
 
 				umount /root/sys
 				umount /root/proc
@@ -381,6 +397,16 @@ Arguments ()
 				export EXPOSED_ROOT
 				;;
 
+			plainroot)
+				PLAIN_ROOT="Yes"
+				export PLAIN_ROOT
+				;;
+
+			root=*)
+				ROOT="${ARGUMENT#root=}"
+				export ROOT
+				;;
+
 			union=*)
 				UNIONTYPE="${ARGUMENT#union=}"
 				export UNIONTYPE
@@ -394,6 +420,11 @@ Arguments ()
 			xdebconf)
 				XDEBCONF="Yes"
 				export XDEBCONF
+				;;
+
+			xdriver=*)
+			        XDRIVER="${ARGUMENT#xdriver=}"
+				export XDRIVER
 				;;
 
 			xvideomode=*)
@@ -425,7 +456,7 @@ Arguments ()
 
 	if [ -z "${UNIONTYPE}" ]
 	then
-		UNIONTYPE="unionfs"
+		UNIONTYPE="aufs"
 		export UNIONTYPE
 	fi
 }
@@ -436,7 +467,7 @@ is_live_path ()
 
 	if [ -d "${DIRECTORY}"/"${LIVE_MEDIA_PATH}" ]
 	then
-		for FILESYSTEM in squashfs ext2 ext3 xfs dir
+		for FILESYSTEM in squashfs ext2 ext3 xfs dir jffs2
 		do
 			if [ "$(echo ${DIRECTORY}/${LIVE_MEDIA_PATH}/*.${FILESYSTEM})" != "${DIRECTORY}/${LIVE_MEDIA_PATH}/*.${FILESYSTEM}" ]
 			then
@@ -458,7 +489,7 @@ matches_uuid ()
 	path="${1}"
 	uuid="$(cat /conf/uuid.conf)"
 
-	for try_uuid_file in "${mountpoint}/.disk/casper-uuid"*
+	for try_uuid_file in "${mountpoint}/.disk/live-uuid"*
 	do
 		[ -e "${try_uuid_file}" ] || continue
 
@@ -476,8 +507,8 @@ matches_uuid ()
 get_backing_device ()
 {
 	case "${1}" in
-		*.squashfs|*.ext2|*.ext3)
-			echo $(setup_loop "${1}" "loop" "/sys/block/loop*" '0' "${LIVE_MEDIA_ENCRYPTION}")
+		*.squashfs|*.ext2|*.ext3|*.jffs2)
+			echo $(setup_loop "${1}" "loop" "/sys/block/loop*" '0' "${LIVE_MEDIA_ENCRYPTION}" "${2}")
 			;;
 
 		*.dir)
@@ -513,6 +544,7 @@ mount_images_in_directory ()
 	if match_files_in_dir "${directory}/${LIVE_MEDIA_PATH}/*.squashfs" ||
 		match_files_in_dir "${directory}/${LIVE_MEDIA_PATH}/*.ext2" ||
 		match_files_in_dir "${directory}/${LIVE_MEDIA_PATH}/*.ext3" ||
+		match_files_in_dir "${directory}/${LIVE_MEDIA_PATH}/*.jffs2" ||
 		match_files_in_dir "${directory}/${LIVE_MEDIA_PATH}/*.dir"
 	then
 		[ -n "${mac}" ] && adddirectory="${directory}/${LIVE_MEDIA_PATH}/${mac}"
@@ -530,20 +562,6 @@ is_nice_device ()
 	then
 		return 0
 	fi
-
-	return 1
-}
-
-is_supported_fs ()
-{
-	# FIXME: do something better like the scan of supported filesystems
-	fstype="${1}"
-
-	case ${fstype} in
-		vfat|iso9660|udf|ext2|ext3|ntfs)
-			return 0
-			;;
-	esac
 
 	return 1
 }
@@ -607,7 +625,7 @@ copy_live_to ()
 		cd "${copyto}"
 		tar zxf "${copyfrom}/${LIVE_MEDIA_PATH}/$(basename ${FETCH})"
 		rm -f "${copyfrom}/${LIVE_MEDIA_PATH}/$(basename ${FETCH})"
-		mount -r --move "${copyto}" "${rootmnt}"
+		mount -r -o move "${copyto}" "${rootmnt}"
 		cd "${OLDPWD}"
 	else
 		if [ -n "${MODULETORAMFILE}" ]
@@ -619,7 +637,7 @@ copy_live_to ()
 
 		livefs_root
 		umount ${copyfrom}
-		mount -r --move ${copyto} ${copyfrom}
+		mount -r -o move ${copyto} ${copyfrom}
 	fi
 
 	rmdir ${copyto}
@@ -632,8 +650,16 @@ do_netmount ()
 
 	modprobe -q af_packet # For DHCP
 
-	udevtrigger
-	udevsettle
+	if [ -x /sbin/udevadm ]
+	then
+		# lenny
+		udevadm trigger
+		udevadm settle
+	else
+		# etch
+		udevtrigger
+		udevsettle
+	fi
 
 	ipconfig ${DEVICE} | tee /netboot.config
 
@@ -648,7 +674,7 @@ do_netmount ()
 		NFSROOT=${ROOTSERVER}:${ROOTPATH}
 	fi
 
-	if [ -n "${FETCH}" ] && do_httpmount
+	if ( [ -n "${FETCH}" ] || [ -n "${HTTPFS}" ] || [ -n "${FTPFS}" ] ) && do_httpmount
 	then
 		rc=0
 		return ${rc}
@@ -678,20 +704,53 @@ do_netmount ()
 do_httpmount ()
 {
 	rc=1
-	extension=$(echo "${FETCH}" | sed 's/\(.*\)\.\(.*\)/\2/')
+	dest="${mountpoint}/${LIVE_MEDIA_PATH}"
+	mount -t ramfs ram "${mountpoint}"
+	mkdir -p "${dest}"
 
-	case "${extension}" in
-		squashfs|tgz|tar)
-			[ "${quiet}" != "y" ] && log_begin_msg "Trying wget ${FETCH} -O ${mountpoint}/$(basename ${FETCH})"
-			mkdir -p "${mountpoint}/${LIVE_MEDIA_PATH}"
-			wget "${FETCH}" -O "${mountpoint}/${LIVE_MEDIA_PATH}/$(basename ${FETCH})"
-			[ ${?} -eq 0 ] && rc=0
-			[ "${extension}" = "tgz" ] && live_dest="ram"
-			;;
+	for webfile in HTTPFS FTPFS FETCH
+	do
+		url="$(eval echo \"\$\{${webfile}\}\")"
+		extension="$(echo "${url}" | sed 's/\(.*\)\.\(.*\)/\2/')"
 
-		*)
-			[ "${quiet}" != "y" ] && log_begin_msg "Unrecognized archive extension for ${FETCH}"
-	esac
+		if [ -n "$url" ]
+		then
+			case "${extension}" in
+				squashfs|tgz|tar)
+					if [ "${webfile}" = "FETCH" ]
+					then
+						[ "${quiet}" != "y" ] &&
+							log_begin_msg "Trying wget ${url} -O ${dest}/$(basename ${url})"
+						wget "${url}" -O "${dest}/$(basename ${url})"
+					else
+						[ "${quiet}" != "y" ] &&
+							log_begin_msg "Trying to mount ${url} on ${dest}/$(basename ${url})"
+						if [ "${webfile}" = "FTPFS" ]
+						then
+							FUSE_MOUNT="curlftpfs"
+							url="$(dirname ${url})"
+						else
+							FUSE_MOUNT="httpfs"
+						fi
+						modprobe fuse
+						$FUSE_MOUNT "${url}" "${dest}"
+					fi
+					[ ${?} -eq 0 ] && rc=0
+					[ "${extension}" = "tgz" ] && live_dest="ram"
+					break
+					;;
+
+				*)
+					[ "${quiet}" != "y" ] && log_begin_msg "Unrecognized archive extension for ${url}"
+					;;
+			esac
+		fi
+	done
+
+	if [ ${rc} != 0 ]
+	then
+	    umount "${mountpoint}"
+	fi
 
 	return ${rc}
 }
@@ -804,7 +863,7 @@ try_snap ()
 	snap_label="${1}"
 	snap_mount="${2}"
 	snap_type="${3}"
-	snapdata=$(find_files "${snap_label}.squashfs ${snap_label}.cpio.gz ${snap_label}.ext2 ${snap_label}.ext3")
+	snapdata=$(find_files "${snap_label}.squashfs ${snap_label}.cpio.gz ${snap_label}.ext2 ${snap_label}.ext3 ${snap_label}.jffs2")
 
 	if [ ! -z "${snapdata}" ]
 	then
@@ -812,9 +871,9 @@ try_snap ()
 		snapback="$(echo ${snapdata} | cut -f2 -d ' ')"
 		snapfile="$(echo ${snapdata} | cut -f3 -d ' ')"
 
-		if echo "${snapfile}" | grep -qs '\(squashfs\|ext2\|ext3\)'
+		if echo "${snapfile}" | grep -qs '\(squashfs\|ext2\|ext3\|jffs2\)'
 		then
-			# squashfs or ext2/ext3 snapshot
+			# squashfs, jffs2 or ext2/ext3 snapshot
 			dev=$(get_backing_device "${snapback}/${snapfile}")
 
 			if ! do_snap_copy "${dev}" "${snap_mount}" "${snap_type}"
@@ -824,7 +883,7 @@ try_snap ()
 			fi
 		else
 			# cpio.gz snapshot
-			if ! (cd "${snap_mount}" && zcat "${snapback}/${snapfile}" | cpio -i -u -d 2>/dev/null)
+			if ! (cd "${snap_mount}" && zcat "${snapback}/${snapfile}" | cpio --extract --preserve-modification-time --no-absolute-filenames --sparse --unconditional --make-directories > /dev/null 2>&1)
 			then
 				log_warning_msg "Impossible to include the ${snapfile} Snapshot"
 				return 1
@@ -891,6 +950,9 @@ setup_unionfs ()
 	then
 		# go aroung a bug in nfs-unionfs locking for unionfs <= 1.4
 		roopt="nfsro"
+	elif [ "${UNIONTYPE}" = "aufs" ]
+	then
+		roopt="rr"
 	else
 		roopt="ro"
 	fi
@@ -910,7 +972,7 @@ setup_unionfs ()
 		done
 	else
 		# ${MODULE}.module does not exist, create a list of images
-		for FILESYSTEM in squashfs ext2 ext3 xfs dir
+		for FILESYSTEM in squashfs ext2 ext3 xfs jffs2 dir
 		do
 			for IMAGE in "${image_directory}"/*."${FILESYSTEM}"
 			do
@@ -923,7 +985,7 @@ setup_unionfs ()
 
 		if [ -n "${addimage_directory}" ] && [ -d "${addimage_directory}" ]
 		then
-			for FILESYSTEM in squashfs ext2 ext3 xfs dir
+			for FILESYSTEM in squashfs ext2 ext3 xfs jffs2 dir
 			do
 				for IMAGE in "${addimage_directory}"/*."${FILESYSTEM}"
 				do
@@ -954,7 +1016,12 @@ setup_unionfs ()
 			rofslist="${image} ${rofslist}"
 		elif [ -f "${image}" ]
 		then
-			backdev=$(get_backing_device "${image}")
+			if /sbin/losetup --help 2>&1 | grep -q -- "-r\b"
+			then
+				backdev=$(get_backing_device "${image}" "-r")
+			else
+				backdev=$(get_backing_device "${image}")
+			fi
 			fstype=$(get_fstype "${backdev}")
 
 			if [ "${fstype}" = "unknown" ]
@@ -963,7 +1030,7 @@ setup_unionfs ()
 			fi
 
 			mkdir -p "${croot}/${imagename}"
-			echo "debug: Can not mount backdev ${backdev} (image = ${image}) on croot/imagename ${croot}/${imagename}"
+			echo "debug: Mounting backdev \"${backdev}\" (image = ${image}) on croot/imagename \"${croot}/${imagename}\""
 			mount -t "${fstype}" -o ro,noatime "${backdev}" "${croot}/${imagename}" || panic "Can not mount ${backdev} (${image}) on ${croot}/${imagename}" && rofsstring="${croot}/${imagename}=${roopt}:${rofsstring}" && rofslist="${croot}/${imagename} ${rofslist}"
 		fi
 	done
@@ -973,20 +1040,54 @@ setup_unionfs ()
 	mkdir -p /cow
 
 	# Looking for "${root_persistence}" device or file
-	if [ -n "${PERSISTENT}" ]
+	if [ -n "${PERSISTENT}" ] && [ -z "${NOPERSISTENT}" ]
 	then
+		# Load USB modules
+		num_block=$(ls -l /sys/block | wc -l)
+		for module in sd_mod uhci-hcd ehci-hcd ohci-hcd usb-storage
+		do
+			modprobe -q -b ${module}
+		done
+
+		if [ -x /sbin/udevadm ]
+		then
+			# lenny
+			udevadm trigger
+			udevadm settle
+		else
+			# etch
+			udevtrigger
+			udevsettle
+		fi
+
+		# For some reason, udevsettle does not block in this scenario,
+		# so we sleep for a little while.
+		#
+		# See https://bugs.launchpad.net/ubuntu/+source/casper/+bug/84591
+		for timeout in 5 4 3 2 1
+		do
+			sleep 1
+
+			if [ $(ls -l /sys/block | wc -l) -gt ${num_block} ]
+			then
+				break
+			fi
+		done
+
 		cowprobe=$(find_cow_device "${root_persistence}")
 
 		if [ -b "${cowprobe}" ]
 		then
 			cowdevice=${cowprobe}
 			cow_fstype=$(get_fstype "${cowprobe}")
+			cow_mountopt="rw,noatime"
 		else
 			[ "${quiet}" != "y" ] && log_warning_msg "Unable to find the persistent medium"
 			cowdevice="tmpfs"
 			cow_fstype="tmpfs"
+			cow_mountopt="rw,noatime,mode=755"
 		fi
-	elif [ -n "${NFS_COW}" ]
+	elif [ -n "${NFS_COW}" ] && [ -z "${NOPERSISTENT}" ]
 	then
 		# check if there are any nfs options
 		if echo ${NFS_COW}|grep -q ','
@@ -1015,10 +1116,10 @@ setup_unionfs ()
 		[ "${quiet}" != "y" ] && log_begin_msg \
 			"Trying nfsmount ${nfs_cow_opts} ${cowdevice} /cow"
 		nfsmount ${nfs_cow_opts} ${cowdevice} /cow || \
-			panic "Can not mount ${cowdevice} on /cow"
+			panic "Can not mount ${cowdevice} (n: ${cow_fstype}) on /cow"
 	else
-		mount ${cowdevice} -t ${cow_fstype} -o rw,noatime /cow || \
-			panic "Can not mount ${cowdevice} on /cow"
+		mount -t ${cow_fstype} -o ${cow_mountopt} ${cowdevice} /cow || \
+			panic "Can not mount ${cowdevice} (o: ${cow_fstype}) on /cow"
 	fi
 
 	rofscount=$(echo ${rofslist} |wc -w)
@@ -1056,7 +1157,7 @@ setup_unionfs ()
 	mount -t tmpfs tmpfs ${rootmnt}/live
 
 	# Adding other custom mounts
-	if [ -n "${PERSISTENT}" ]
+	if [ -n "${PERSISTENT}" ] && [ -z "${NOPERSISTENT}" ]
 	then
 		# directly mount /home
 		# FIXME: add a custom mounts configurable system
@@ -1087,7 +1188,7 @@ setup_unionfs ()
 					;;
 
 				*)
-					mount --move "${d}" "${rootmnt}/live/${d##*/}"
+					mount -o move "${d}" "${rootmnt}/live/${d##*/}"
 					;;
 			esac
 		done
@@ -1095,7 +1196,7 @@ setup_unionfs ()
 
 	# shows cow fs on /cow for use by live-snapshot
 	mkdir -p "${rootmnt}/live/cow"
-	mount -o move /cow "${rootmnt}/live/cow"
+	mount -o move /cow "${rootmnt}/live/cow" || mount -o bind /cow "${rootmnt}/live/cow" || [ "${quiet}" != "y" ] && log_warning_msg "Unable to move or bind /cow to ${rootmnt}/live/cow"
 }
 
 check_dev ()
@@ -1107,6 +1208,19 @@ check_dev ()
 	if [ -z "${devname}" ]
 	then
 		devname=$(sys2dev "${sysdev}")
+	fi
+
+	if [ -d "${devname}" ]
+	then
+		mount -o bind "${devname}" $mountpoint || continue
+
+		if is_live_path $mountpoint
+		then
+			echo $mountpoint
+			return 0
+		else
+			umount $mountpoint
+		fi
 	fi
 
 	if [ -n "${LIVE_MEDIA_OFFSET}" ]
@@ -1162,7 +1276,7 @@ find_livefs ()
 	fi
 
 	# or do the scan of block devices
-	for sysblock in $(echo /sys/block/* | tr ' ' '\n' | grep -v loop | grep -v ram)
+	for sysblock in $(echo /sys/block/* | tr ' ' '\n' | grep -v loop | grep -v ram | grep -v 'dm-' | grep -v fd )
 	do
 		devname=$(sys2dev "${sysblock}")
 		fstype=$(get_fstype "${devname}")
@@ -1184,7 +1298,8 @@ find_livefs ()
 			done
 		elif [ "${fstype}" = "squashfs" -o \
 			"${fstype}" = "ext2" -o \
-			"${fstype}" = "ext3" ]
+			"${fstype}" = "ext3" -o \
+			"${fstype}" = "jffs2" ]
 		then
 			# This is an ugly hack situation, the block device has
 			# an image directly on it.  It's hopefully
@@ -1198,14 +1313,6 @@ find_livefs ()
 	return 1
 }
 
-pulsate ()
-{
-	if [ -x /sbin/usplash_write ]
-	then
-		/sbin/usplash_write "PULSATE"
-	fi
-}
-
 set_usplash_timeout ()
 {
 	if [ -x /sbin/usplash_write ]
@@ -1216,16 +1323,22 @@ set_usplash_timeout ()
 
 mountroot ()
 {
+    
+        if [ -x /scripts/local-top/cryptroot ]; then
+	    /scripts/local-top/cryptroot
+	fi
+
 	exec 6>&1
 	exec 7>&2
 	exec > live.log
 	exec 2>&1
+	tail -f live.log >&7 &
+	tailpid="${!}"
 
 	Arguments
 
 	set_usplash_timeout
 	[ "${quiet}" != "y" ] && log_begin_msg "Running /scripts/live-premount"
-	pulsate
 	run_scripts /scripts/live-premount
 	[ "${quiet}" != "y" ] && log_end_msg
 
@@ -1234,7 +1347,7 @@ mountroot ()
 
 	set_usplash_timeout
 
-	if [ ! -z "${NETBOOT}" ] || [ ! -z "${FETCH}" ]
+	if [ ! -z "${NETBOOT}" ] || [ ! -z "${FETCH}" ] || [ ! -z "${HTTPFS}" ] || [ ! -z "${FTPFS}" ]
 	then
 		if do_netmount
 		then
@@ -1243,18 +1356,24 @@ mountroot ()
 			panic "Unable to find a live file system on the network"
 		fi
 	else
-		# Scan local devices for the image
-		for i in 0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19
-		do
-			livefs_root=$(find_livefs ${i})
+		if [ -n "${PLAIN_ROOT}" ] && [ -n "${ROOT}" ]
+		then
+			# Do a local boot from hd
+			livefs_root=${ROOT}
+		else
+			# Scan local devices for the image
+			for i in 0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19
+			do
+				livefs_root=$(find_livefs ${i})
 
-			if [ -n "${livefs_root}" ]
-			then
-				break
-			fi
+				if [ -n "${livefs_root}" ]
+				then
+					break
+				fi
 
-			sleep 1
-		done
+				sleep 1
+			done
+		fi
 	fi
 
 	if [ -z "${livefs_root}" ]
@@ -1291,11 +1410,11 @@ mountroot ()
 	maybe_break live-bottom
 	[ "${quiet}" != "y" ] && log_begin_msg "Running /scripts/live-bottom"
 
-	pulsate
 	run_scripts /scripts/live-bottom
 	[ "${quiet}" != "y" ] && log_end_msg
 
 	exec 1>&6 6>&-
 	exec 2>&7 7>&-
+	kill ${tailpid}
 	cp live.log "${rootmnt}/var/log/"
 }
